import { mkdir, readdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { dirname } from "node:path";
import { resolve } from "node:path";
import { assertIdentityId } from "../identity/contracts.js";
import type { CommunityComment, CommunityPost, CommunityReport } from "./contracts.js";
import { withDurableCommunityContentLock } from "./content-lock.js";
import { withDurableCommunityLikeLock } from "./like-lock.js";
import { withDurableCommunityReportLock } from "./report-lock.js";

async function saveJson(path: string, value: unknown): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${process.pid}.${randomBytes(4).toString("hex")}.tmp`; await writeFile(temporary, JSON.stringify(value, null, 2), "utf8"); await rename(temporary, path); }
async function loadJson<T>(path: string): Promise<T | null> { try { return JSON.parse(await readFile(path, "utf8")) as T; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return null; throw error; } }

function postPath(root: string, postId: string): string { assertIdentityId(postId); return resolve(root, "community", "posts", `${postId}.json`); }
function likePath(root: string, postId: string, userId: string): string { assertIdentityId(postId); assertIdentityId(userId); return resolve(root, "community", "likes", postId, `${userId}.json`); }
function commentPath(root: string, postId: string, commentId: string): string { assertIdentityId(postId); assertIdentityId(commentId); return resolve(root, "community", "comments", postId, `${commentId}.json`); }
function reportPath(root: string, reportId: string): string { assertIdentityId(reportId); return resolve(root, "community", "reports", `${reportId}.json`); }
export const savePostUnlocked = (root: string, post: CommunityPost) => saveJson(postPath(root, post.id), post);
export const savePost = (root: string, post: CommunityPost) => withDurableCommunityContentLock(root, post.id, () => savePostUnlocked(root, post), { waitForMs: 2_000 });
export const loadPostUnlocked = (root: string, postId: string) => loadJson<CommunityPost>(postPath(root, postId));
export const loadPost = (root: string, postId: string) => withDurableCommunityContentLock(root, postId, () => loadPostUnlocked(root, postId), { waitForMs: 2_000 });
export async function listPostsUnlocked(root: string): Promise<CommunityPost[]> { let names: string[]; try { names = await readdir(resolve(root, "community", "posts")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } const result: CommunityPost[] = []; for (const name of names.filter((item) => item.endsWith(".json"))) { const post = await loadJson<CommunityPost>(resolve(root, "community", "posts", name)); if (post) result.push(post); } return result; }
export async function listPosts(root: string): Promise<CommunityPost[]> { const candidates = await listPostsUnlocked(root); const result: CommunityPost[] = []; for (const candidate of candidates) { try { assertIdentityId(candidate.id); } catch { continue; } await withDurableCommunityContentLock(root, candidate.id, async () => { const current = await loadPostUnlocked(root, candidate.id); if (current?.id === candidate.id) result.push(current); }, { waitForMs: 2_000 }); } return result; }
export const saveCommentUnlocked = (root: string, comment: CommunityComment) => saveJson(commentPath(root, comment.postId, comment.id), comment);
export const saveComment = (root: string, comment: CommunityComment) => withDurableCommunityContentLock(root, comment.postId, () => saveCommentUnlocked(root, comment), { waitForMs: 2_000 });
export const loadCommentUnlocked = (root: string, postId: string, commentId: string) => loadJson<CommunityComment>(commentPath(root, postId, commentId));
export const loadComment = (root: string, postId: string, commentId: string) => withDurableCommunityContentLock(root, postId, () => loadCommentUnlocked(root, postId, commentId), { waitForMs: 2_000 });
export async function listCommentsUnlocked(root: string, postId: string): Promise<CommunityComment[]> { let names: string[]; try { names = await readdir(resolve(root, "community", "comments", postId)); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } const result: CommunityComment[] = []; for (const name of names.filter((item) => item.endsWith(".json"))) { const comment = await loadJson<CommunityComment>(resolve(root, "community", "comments", postId, name)); if (comment) result.push(comment); } return result; }
export const listComments = (root: string, postId: string) => withDurableCommunityContentLock(root, postId, () => listCommentsUnlocked(root, postId), { waitForMs: 2_000 });
export const saveReportUnlocked = (root: string, report: CommunityReport) => saveJson(reportPath(root, report.id), report);
export const saveReport = (root: string, report: CommunityReport) => withDurableCommunityReportLock(root, report.reporterUserId, report.targetType, report.postId, report.targetId, () => saveReportUnlocked(root, report), { waitForMs: 2_000 });
export const loadReportUnlocked = (root: string, reportId: string) => loadJson<CommunityReport>(reportPath(root, reportId));
export async function loadReport(root: string, reportId: string): Promise<CommunityReport | null> { const candidate = await loadReportUnlocked(root, reportId); if (!candidate) return null; return withDurableCommunityReportLock(root, candidate.reporterUserId, candidate.targetType, candidate.postId, candidate.targetId, () => loadReportUnlocked(root, reportId), { waitForMs: 2_000 }); }
export async function listReportsUnlocked(root: string): Promise<CommunityReport[]> { let names: string[]; try { names = await readdir(resolve(root, "community", "reports")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } const result: CommunityReport[] = []; for (const name of names.filter((item) => item.endsWith(".json"))) { const report = await loadJson<CommunityReport>(resolve(root, "community", "reports", name)); if (report) result.push(report); } return result; }
export async function listReports(root: string): Promise<CommunityReport[]> { const candidates = await listReportsUnlocked(root); const result: CommunityReport[] = []; for (const candidate of candidates) { try { assertIdentityId(candidate.reporterUserId); assertIdentityId(candidate.postId); assertIdentityId(candidate.targetId); } catch { continue; } await withDurableCommunityReportLock(root, candidate.reporterUserId, candidate.targetType, candidate.postId, candidate.targetId, async () => { const current = await loadReportUnlocked(root, candidate.id); if (current?.id === candidate.id) result.push(current); }, { waitForMs: 2_000 }); } return result; }
export const hasLikeUnlocked = async (root: string, postId: string, userId: string): Promise<boolean> => Boolean(await loadJson<{ postId: string; userId: string }>(likePath(root, postId, userId)));
export const hasLike = (root: string, postId: string, userId: string) => withDurableCommunityLikeLock(root, postId, userId, () => hasLikeUnlocked(root, postId, userId), { waitForMs: 2_000 });
export const saveLikeUnlocked = (root: string, postId: string, userId: string) => saveJson(likePath(root, postId, userId), { postId, userId });
export const saveLike = (root: string, postId: string, userId: string) => withDurableCommunityLikeLock(root, postId, userId, () => saveLikeUnlocked(root, postId, userId), { waitForMs: 2_000 });
export async function removeLikeUnlocked(root: string, postId: string, userId: string): Promise<void> { const file = likePath(root, postId, userId); try { await unlink(file); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } }
export const removeLike = (root: string, postId: string, userId: string) => withDurableCommunityLikeLock(root, postId, userId, () => removeLikeUnlocked(root, postId, userId), { waitForMs: 2_000 });
export async function countLikesUnlocked(root: string, postId: string): Promise<number> { try { return (await readdir(resolve(root, "community", "likes", postId))).filter((item) => item.endsWith(".json")).length; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return 0; throw error; } }
export async function countLikes(root: string, postId: string): Promise<number> { let names: string[]; try { names = await readdir(resolve(root, "community", "likes", postId)); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return 0; throw error; } let count = 0; for (const name of names.filter((item) => item.endsWith(".json"))) { const userId = name.slice(0, -5); try { assertIdentityId(userId); } catch { continue; } await withDurableCommunityLikeLock(root, postId, userId, async () => { if (await hasLikeUnlocked(root, postId, userId)) count += 1; }, { waitForMs: 2_000 }); } return count; }
