import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { AddressInfo } from "node:net";
import test from "node:test";
import { createActivityService } from "../src/activity/service.js";
import { createGrowthService } from "../src/growth/read-model.js";
import { createPlatformUserService } from "../src/platform-user/service.js";
import { createTeamService } from "../src/teams/service.js";
import { createUserProjectService } from "../src/project-model/user-project-service.js";
import { createAiTeamProposalService } from "../src/ai-team/service.js";
import { startWebControlPlaneServer } from "../src/web-control-plane/server.js";

test("AI team proposal API keeps Runtime waiting and human acceptance separate from execution", async () => {
  const root = await mkdtemp(join(tmpdir(), "iseol-ai-team-proposal-api-"));
  const now = "2026-09-27T13:00:00.000Z";
  const platformRoot = join(root, "platform");
  const platform = createPlatformUserService(platformRoot, { now: () => now });
  const activity = createActivityService(platformRoot, { now: () => now });
  const growth = createGrowthService(platformRoot, { now: () => now });
  const owner = await platform.createUser({ id: "ai-proposal-api-owner", email: "ai-proposal-owner@example.com", displayName: "AI proposal owner", timezone: "Asia/Seoul" });
  const outsider = await platform.createUser({ id: "ai-proposal-api-outsider", email: "ai-proposal-outsider@example.com", displayName: "Outsider", timezone: "Asia/Seoul" });
  const ownerSession = await platform.createSession({ userId: owner.id, roles: ["user"], expiresAt: "2026-09-28T13:00:00.000Z" });
  const outsiderSession = await platform.createSession({ userId: outsider.id, roles: ["user"], expiresAt: "2026-09-28T13:00:00.000Z" });
  const ownerPrincipal = await platform.resolveAuthenticatedPrincipal(ownerSession.token);
  assert.ok(ownerPrincipal);
  const teams = createTeamService(platformRoot, { now: () => now });
  const team = await teams.createTeam(ownerPrincipal!, { name: "Proposal API team", description: "owner approval boundary", kind: "project", visibility: "public", capacity: 4 });
  await teams.addAiMember(ownerPrincipal!, team.id, { agentId: "api-frontend", assignmentRole: "frontend", capabilities: ["task.propose"], approvalScope: "owner-approved-execution" }, now);
  const projects = createUserProjectService({ platformRoot, projectModelRoot: join(root, "project-model"), projectHarnessRoot: join(root, "runs"), iseolRoot: root, canAccessTeam: (principal, teamId) => teams.canAccess(principal, teamId), canAccessTeamWithinMembershipLock: (principal, teamId) => teams.canAccessWithinMembershipLock(principal, teamId), activityService: activity, now: () => now });
  const proposals = createAiTeamProposalService({ root: join(platformRoot, "ai-team"), teamService: teams, userProjectService: projects, activityService: activity, now: () => now, dispatcher: async () => ({ status: "proposed", draft: { title: "API boundary task", objective: "Document the bounded proposal", acceptanceCriteria: ["owner review is required"], rationale: "Keep AI execution controlled" } }) });
  const server = await startWebControlPlaneServer({ host: "127.0.0.1", port: 0, token: "operator", modelRoot: join(root, "model"), harnessRoot: join(root, "harness"), webRoot: join(root, "web"), userService: platform, teamService: teams, activityService: activity, growthService: growth, userProjectService: projects, aiTeamProposalService: proposals });
  const url = "http://127.0.0.1:" + (server.address() as AddressInfo).port;
  const headers = (token: string) => ({ authorization: "Bearer " + token, "content-type": "application/json" });
  try {
    const projectResponse = await fetch(url + "/api/user/projects", { method: "POST", headers: headers(ownerSession.token), body: JSON.stringify({ name: "Proposal API project", objective: "store AI proposals", purpose: "rapid-prototype", teamMode: "mixed", teamId: team.id }) });
    assert.equal(projectResponse.status, 201);
    const project = (await projectResponse.json() as any).project;
    const proposalResponse = await fetch(url + "/api/user/projects/" + project.id + "/ai-proposals", { method: "POST", headers: headers(ownerSession.token), body: JSON.stringify({ agentId: "api-frontend", requestId: "api-proposal-1" }) });
    assert.equal(proposalResponse.status, 201);
    const proposal = (await proposalResponse.json() as any).proposal;
    assert.equal(proposal.status, "proposed");
    const foreign = await fetch(url + "/api/user/projects/" + project.id + "/ai-proposals", { method: "GET", headers: headers(outsiderSession.token) });
    assert.equal(foreign.status, 400);
    const accepted = await fetch(url + "/api/user/projects/" + project.id + "/ai-proposals/" + proposal.id + "/accept", { method: "POST", headers: headers(ownerSession.token), body: "{}" });
    assert.equal(accepted.status, 200);
    const acceptedBody = await accepted.json() as any;
    assert.equal(acceptedBody.proposal.status, "accepted");
    assert.equal(acceptedBody.workRequest.status, "queued");
    assert.equal(acceptedBody.workRequest.runId, undefined);
    const activityResponse = await fetch(url + "/api/user/activity", { headers: headers(ownerSession.token) });
    const acceptedEvents = (await activityResponse.json() as any).events.filter((item: any) => item.sourceId === proposal.id && item.eventType === "ai.team.proposal.accepted");
    assert.equal(acceptedEvents.length, 1);
    assert.equal(acceptedEvents[0].sourceType, "ai-team-proposal");
    assert.equal(acceptedEvents[0].actorType, "user");
    assert.equal(acceptedEvents[0].verificationStatus, "unverified");
    assert.deepEqual(acceptedEvents[0].payload, { projectId: project.id, teamId: team.id, proposalId: proposal.id, workRequestId: acceptedBody.workRequest.id, agentId: "api-frontend" });
    assert.equal((await (await fetch(url + "/api/user/growth", { headers: headers(ownerSession.token) })).json() as any).xp, 0);
  } finally { await server.closeForShutdown(); }
});
