import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

test("integrations route opens the integration settings section without inventing connection state", async () => {
  const source = await readFile(join(process.cwd(), "user-ui", "src", "pages", "Settings.tsx"), "utf8");
  assert.match(source, /useLocation/);
  assert.match(source, /location\.pathname === ['"]\/integrations['"]/);
  assert.match(source, /연동 환경/);
  assert.match(source, /연동 API 미연결/);
  assert.match(source, /준비 중/);
  assert.match(source, /getRuntimeStatus/);
  assert.match(source, /Runtime 준비됨/);
  assert.match(source, /Runtime 미연결/);
  assert.match(source, /개인 AI Runtime/);
  assert.match(source, /runtimeStatus\?\.aiChat/);
  assert.match(source, /개인 AI 미연결/);
  assert.match(source, /AI 팀 Runtime/);
  assert.match(source, /runtimeStatus\?\.aiTeam/);
  assert.match(source, /AI 팀 미연결/);
  assert.match(source, /학습 AI Runtime/);
  assert.match(source, /runtimeStatus\?\.learningAi/);
  assert.match(source, /학습 AI 미연결/);
  assert.match(source, /runtimeStatus\?\.agent/);
  assert.match(source, /Desktop Agent/);
  assert.match(source, /Agent 준비됨/);
  assert.match(source, /Agent 미연결/);
  assert.match(source, /getUserIntegrations/);
  assert.match(source, /Calendar/);
  assert.match(source, /외부 전달 동의/);
  assert.match(source, /integrationStatus/);
  assert.match(source, /visibilitychange/);
  assert.match(source, /setInterval/);
  assert.match(source, /clearInterval/);
  assert.match(source, /상태 확인 필요/);
  assert.doesNotMatch(source, /해제/);
  assert.doesNotMatch(source, /status:\s*['"]connected['"]/);
});
